### ISSUE TITLE
Compatibility with Ruby on Rails

### ISSUE THREAD

**Issue by javierav** [svoop/minitest-substitute#1]
Ruby on Rails already defines `with` method in Object: https://api.rubyonrails.org/classes/Object.html#method-i-with

**Comment by svoop** [comment]
Ouch, I see. I don't currently have a Rails 7 project (yet), but will bump into this pretty soon when we start upgrading from Rails 6.1 where `Object#with` does not yet exist.

How does this conflict impact you? Do you use `Object#with` from Rails in your tests?

If so, the only way to resolve I see after not giving it much thought: Rename `with` to something else e.g. `using` and only alias it to `with` in case this is not yet defined (for downwards compatibility).

**Comment by svoop** [comment]
I've replaced `with` with `substitute` as of minitest-substitute-1.0.0
