### ISSUE TITLE
Update README to clarify intent

### ISSUE THREAD

**Issue by jbigler** [svoop/minitest-substitute#2]
From the README:
`This comes in very handy when you have to derive from default configuration in order to test some aspects of your code.`

I believe a better word here would be deviate, instead of derive.

`This comes in very handy when you have to deviate from the default configuration in order to test some aspects of your code.`

**Comment by svoop** [comment]
You're absolutely right. 😄 Thanks for the hint, very helpful for a non-native English writer like me!
